// list of songs. don't ask me to update it.
const songList = [
    { id: 1, name: "ANOTHER HIM", file: "DELTARUNESoundtrack/./001 ANOTHER HIM.mp3", rating: 1500, comparisons: 0, duration: 48.04 },
    { id: 2, name: "Beginning", file: "DELTARUNESoundtrack/./002 Beginning.mp3", rating: 1500, comparisons: 0, duration: 57.44 },
    { id: 3, name: "School", file: "DELTARUNESoundtrack/./003 School.mp3", rating: 1500, comparisons: 0, duration: 80.04 },
    { id: 4, name: "Susie", file: "DELTARUNESoundtrack/./004 Susie.mp3", rating: 1500, comparisons: 0, duration: 27.45 },
    { id: 5, name: "The Door", file: "DELTARUNESoundtrack/./005 The Door.mp3", rating: 1500, comparisons: 0, duration: 41.77 },
    { id: 6, name: "Cliffs", file: "DELTARUNESoundtrack/./006 Cliffs.mp3", rating: 1500, comparisons: 0, duration: 35.16 },
    { id: 7, name: "The Chase", file: "DELTARUNESoundtrack/./007 The Chase.mp3", rating: 1500, comparisons: 0, duration: 33.93 },
    { id: 8, name: "The Legend", file: "DELTARUNESoundtrack/./008 The Legend.mp3", rating: 1500, comparisons: 0, duration: 111.31 },
    { id: 9, name: "Lancer", file: "DELTARUNESoundtrack/./009 Lancer.mp3", rating: 1500, comparisons: 0, duration: 48.04 },
    { id: 10, name: "Rude Buster", file: "DELTARUNESoundtrack/./010 Rude Buster.mp3", rating: 1500, comparisons: 0, duration: 75.47 },
    { id: 11, name: "Empty Town", file: "DELTARUNESoundtrack/./011 Empty Town.mp3", rating: 1500, comparisons: 0, duration: 83.51 },
    { id: 12, name: "Weird Birds", file: "DELTARUNESoundtrack/./012 Weird Birds.mp3", rating: 1500, comparisons: 0, duration: 16.67 },
    { id: 13, name: "Field of Hopes and Dreams", file: "DELTARUNESoundtrack/./013 Field of Hopes and Dreams.mp3", rating: 1500, comparisons: 0, duration: 161.31 },
    { id: 14, name: "Fanfare (from Rose of Winter)", file: "DELTARUNESoundtrack/./014 Fanfare (from Rose of Winter).mp3", rating: 1500, comparisons: 0, duration: 15.65 },
    { id: 15, name: "Lantern", file: "DELTARUNESoundtrack/./015 Lantern.mp3", rating: 1500, comparisons: 0, duration: 68.86 },
    { id: 16, name: "I'm Very Bad", file: "DELTARUNESoundtrack/./016 I'm Very Bad.mp3", rating: 1500, comparisons: 0, duration: 13.74 },
    { id: 17, name: "Checker Dance", file: "DELTARUNESoundtrack/./017 Checker Dance.mp3", rating: 1500, comparisons: 0, duration: 78.03 },
    { id: 18, name: "Quiet Autumn", file: "DELTARUNESoundtrack/./018 Quiet Autumn.mp3", rating: 1500, comparisons: 0, duration: 49.82 },
    { id: 19, name: "Scarlet Forest", file: "DELTARUNESoundtrack/./019 Scarlet Forest.mp3", rating: 1500, comparisons: 0, duration: 128.03 },
    { id: 20, name: "Thrash Machine", file: "DELTARUNESoundtrack/./020 Thrash Machine.mp3", rating: 1500, comparisons: 0, duration: 54.88 },
    { id: 21, name: "Vs. Lancer", file: "DELTARUNESoundtrack/./021 Vs. Lancer.mp3", rating: 1500, comparisons: 0, duration: 42.48 },
    { id: 22, name: "Basement", file: "DELTARUNESoundtrack/./022 Basement.mp3", rating: 1500, comparisons: 0, duration: 27.98 },
    { id: 23, name: "Imminent Death", file: "DELTARUNESoundtrack/./023 Imminent Death.mp3", rating: 1500, comparisons: 0, duration: 20.04 },
    { id: 24, name: "Vs. Susie", file: "DELTARUNESoundtrack/./024 Vs. Susie.mp3", rating: 1500, comparisons: 0, duration: 81.11 },
    { id: 25, name: "Card Castle", file: "DELTARUNESoundtrack/./025 Card Castle.mp3", rating: 1500, comparisons: 0, duration: 61.47 },
    { id: 26, name: "Rouxls Kaard", file: "DELTARUNESoundtrack/./026 Rouxls Kaard.mp3", rating: 1500, comparisons: 0, duration: 19.04, felfebFile: "audio/felfeb/feb-dr/Rouxls Kaard (With Lyrics) - The Deltarune Musical [nakPENJ7xko].mp3" },
    { id: 27, name: "April 2012", file: "DELTARUNESoundtrack/./027 April 2012.mp3", rating: 1500, comparisons: 0, duration: 20.58 },
    { id: 28, name: "Hip Shop", file: "DELTARUNESoundtrack/./028 Hip Shop.mp3", rating: 1500, comparisons: 0, duration: 39.63 },
    { id: 29, name: "Gallery", file: "DELTARUNESoundtrack/./029 Gallery.mp3", rating: 1500, comparisons: 0, duration: 12.83 },
    { id: 30, name: "Chaos King", file: "DELTARUNESoundtrack/./030 Chaos King.mp3", rating: 1500, comparisons: 0, duration: 106.16 },
    { id: 31, name: "Darkness Falls", file: "DELTARUNESoundtrack/./031 Darkness Falls.mp3", rating: 1500, comparisons: 0, duration: 67.00 },
    { id: 32, name: "The Circus", file: "DELTARUNESoundtrack/./032 The Circus.mp3", rating: 1500, comparisons: 0, duration: 51.46 },
    { id: 33, name: "THE WORLD REVOLVING", file: "DELTARUNESoundtrack/./033 THE WORLD REVOLVING.mp3", rating: 1500, comparisons: 0, duration: 101.09, felfebFile: "audio/felfeb/feb-dr/The World Revolving (With Lyrics) - The Deltarune Musical [xOdumLCdgZQ].mp3" },
    { id: 34, name: "Friendship", file: "DELTARUNESoundtrack/./034 Friendship.mp3", rating: 1500, comparisons: 0, duration: 160.55 },
    { id: 35, name: "THE HOLY", file: "DELTARUNESoundtrack/./035 THE HOLY.mp3", rating: 1500, comparisons: 0, duration: 48.04 },
    { id: 36, name: "Your Power", file: "DELTARUNESoundtrack/./036 Your Power.mp3", rating: 1500, comparisons: 0, duration: 13.27 },
    { id: 37, name: "A Town Called Hometown", file: "DELTARUNESoundtrack/./037 A Town Called Hometown.mp3", rating: 1500, comparisons: 0, duration: 113.19 },
    { id: 38, name: "You Can Always Come Home", file: "DELTARUNESoundtrack/./038 You Can Always Come Home.mp3", rating: 1500, comparisons: 0, duration: 100.83 },
    { id: 39, name: "Don't Forget", file: "DELTARUNESoundtrack/./039 Don't Forget.mp3", rating: 1500, comparisons: 0, duration: 51.46 },
    { id: 40, name: "Before the Story", file: "DELTARUNESoundtrack/./040 Before the Story.mp3", rating: 1500, comparisons: 0, duration: 88.66 },
    { id: 41, name: "Faint Glow", file: "DELTARUNESoundtrack/./041 Faint Glow.mp3", rating: 1500, comparisons: 0, duration: 77.35 },
    { id: 42, name: "Girl Next Door", file: "DELTARUNESoundtrack/./042 Girl Next Door.mp3", rating: 1500, comparisons: 0, duration: 54.73 },
    { id: 43, name: "My Castle Town", file: "DELTARUNESoundtrack/./043 My Castle Town.mp3", rating: 1500, comparisons: 0, duration: 127.58 },
    { id: 44, name: "Ohhhhohohoho!", file: "DELTARUNESoundtrack/./044 Ohhhhohohoho!.mp3", rating: 1500, comparisons: 0, duration: 9.51 },
    { id: 45, name: "Queen", file: "DELTARUNESoundtrack/./045 Queen.mp3", rating: 1500, comparisons: 0, duration: 56.79 },
    { id: 46, name: "A CYBER'S WORLD-", file: "DELTARUNESoundtrack/./046 A CYBER'S WORLD-.mp3", rating: 1500, comparisons: 0, duration: 166.19 },
    { id: 47, name: "A Simple Diversion", file: "DELTARUNESoundtrack/./047 A Simple Diversion.mp3", rating: 1500, comparisons: 0, duration: 31.37 },
    { id: 48, name: "Almost To The Guys!", file: "DELTARUNESoundtrack/./048 Almost To The Guys!.mp3", rating: 1500, comparisons: 0, duration: 17.89 },
    { id: 49, name: "Cool Beat", file: "DELTARUNESoundtrack/./049 Cool Beat.mp3", rating: 1500, comparisons: 0, duration: 17.50 },
    { id: 50, name: "When I Get Mad I Dance Like This", file: "DELTARUNESoundtrack/./050 When I Get Mad I Dance Like This.mp3", rating: 1500, comparisons: 0, duration: 10.71 },
    { id: 51, name: "Cyber Battle (Solo)", file: "DELTARUNESoundtrack/./051 Cyber Battle (Solo).mp3", rating: 1500, comparisons: 0, duration: 107.55 },
    { id: 52, name: "When I Get Happy I Dance Like This", file: "DELTARUNESoundtrack/./052 When I Get Happy I Dance Like This.mp3", rating: 1500, comparisons: 0, duration: 19.23 },
    { id: 53, name: "Sound Studio", file: "DELTARUNESoundtrack/./053 Sound Studio.mp3", rating: 1500, comparisons: 0, duration: 68.91 },
    { id: 54, name: "Berdly", file: "DELTARUNESoundtrack/./054 Berdly.mp3", rating: 1500, comparisons: 0, duration: 46.05 },
    { id: 55, name: "Smart Race", file: "DELTARUNESoundtrack/./055 Smart Race.mp3", rating: 1500, comparisons: 0, duration: 66.14 },
    { id: 56, name: "Faint Courage (Game Over)", file: "DELTARUNESoundtrack/./056 Faint Courage (Game Over).mp3", rating: 1500, comparisons: 0, duration: 52.09 },
    { id: 57, name: "WELCOME TO THE CITY", file: "DELTARUNESoundtrack/./057 WELCOME TO THE CITY.mp3", rating: 1500, comparisons: 0, duration: 114.05 },
    { id: 58, name: "Mini Studio", file: "DELTARUNESoundtrack/./058 Mini Studio.mp3", rating: 1500, comparisons: 0, duration: 51.77 },
    { id: 59, name: "Holiday Studio", file: "DELTARUNESoundtrack/./059 Holiday Studio.mp3", rating: 1500, comparisons: 0, duration: 68.91 },
    { id: 60, name: "Cool Mixtape", file: "DELTARUNESoundtrack/./060 Cool Mixtape.mp3", rating: 1500, comparisons: 0, duration: 26.70 },
    { id: 61, name: "HEY EVERY !", file: "DELTARUNESoundtrack/./061 HEY EVERY !.mp3", rating: 1500, comparisons: 0, duration: 18.96 },
    { id: 62, name: "Spamton", file: "DELTARUNESoundtrack/./062 Spamton.mp3", rating: 1500, comparisons: 0, duration: 43.00 },
    { id: 63, name: "NOW'S YOUR CHANCE TO BE A", file: "DELTARUNESoundtrack/./063 NOW'S YOUR CHANCE TO BE A.mp3", rating: 1500, comparisons: 0, duration: 67.32 },
    { id: 64, name: "Elegant Entrance", file: "DELTARUNESoundtrack/./064 Elegant Entrance.mp3", rating: 1500, comparisons: 0, duration: 78.03 },
    { id: 65, name: "Bluebird of Misfortune", file: "DELTARUNESoundtrack/./065 Bluebird of Misfortune.mp3", rating: 1500, comparisons: 0, duration: 49.53 },
    { id: 66, name: "Pandora Palace", file: "DELTARUNESoundtrack/./066 Pandora Palace.mp3", rating: 1500, comparisons: 0, duration: 99.63 },
    { id: 67, name: "KEYGEN", file: "DELTARUNESoundtrack/./067 KEYGEN.mp3", rating: 1500, comparisons: 0, duration: 15.28 },
    { id: 68, name: "Acid Tunnel of Love", file: "DELTARUNESoundtrack/./068 Acid Tunnel of Love.mp3", rating: 1500, comparisons: 0, duration: 90.49 },
    { id: 69, name: "It's Pronounced -Rules-", file: "DELTARUNESoundtrack/./069 It's Pronounced -Rules-.mp3", rating: 1500, comparisons: 0, duration: 61.28 },
    { id: 70, name: "Lost Girl", file: "DELTARUNESoundtrack/./070 Lost Girl.mp3", rating: 1500, comparisons: 0, duration: 80.04 },
    { id: 71, name: "Ferris Wheel", file: "DELTARUNESoundtrack/./071 Ferris Wheel.mp3", rating: 1500, comparisons: 0, duration: 79.23 },
    { id: 72, name: "Attack of the Killer Queen", file: "DELTARUNESoundtrack/./072 Attack of the Killer Queen.mp3", rating: 1500, comparisons: 0, duration: 120.03, felfebFile: "audio/felfeb/feb-dr/Attack Of The Killer Queen (With Lyrics) - The Deltarune Musical [FJN8IUVRCiQ].mp3" },
    { id: 73, name: "Giga Size", file: "DELTARUNESoundtrack/./073 Giga Size.mp3", rating: 1500, comparisons: 0, duration: 107.55 },
    { id: 74, name: "Powers Combined", file: "DELTARUNESoundtrack/./074 Powers Combined.mp3", rating: 1500, comparisons: 0, duration: 16.48 },
    { id: 75, name: "Knock You Down !!", file: "DELTARUNESoundtrack/./075 Knock You Down !!.mp3", rating: 1500, comparisons: 0, duration: 146.49 },
    { id: 76, name: "The Dark Truth", file: "DELTARUNESoundtrack/./076 The Dark Truth.mp3", rating: 1500, comparisons: 0, duration: 72.05 },
    { id: 77, name: "Digital Roots", file: "DELTARUNESoundtrack/./077 Digital Roots.mp3", rating: 1500, comparisons: 0, duration: 33.85 },
    { id: 78, name: "Deal Gone Wrong", file: "DELTARUNESoundtrack/./078 Deal Gone Wrong.mp3", rating: 1500, comparisons: 0, duration: 31.37 },
    { id: 79, name: "BIG SHOT", file: "DELTARUNESoundtrack/./079 BIG SHOT.mp3", rating: 1500, comparisons: 0, duration: 142.32, felfebFile: "audio/felfeb/feb-dr/Big Shot (With Lyrics) - The Deltarune Musical [BppnZ04W1Tk].mp3" },
    { id: 80, name: "A Real Boy!", file: "DELTARUNESoundtrack/./080 A Real Boy!.mp3", rating: 1500, comparisons: 0, duration: 15.70 },
    { id: 81, name: "Dialtone", file: "DELTARUNESoundtrack/./081 Dialtone.mp3", rating: 1500, comparisons: 0, duration: 44.36 },
    { id: 82, name: "sans.", file: "DELTARUNESoundtrack/./082 sans..mp3", rating: 1500, comparisons: 0, duration: 50.65 },
    { id: 83, name: "Chill Jailbreak Alarm To Study And Relax To", file: "DELTARUNESoundtrack/./083 Chill Jailbreak Alarm To Study And Relax To.mp3", rating: 1500, comparisons: 0, duration: 24.03 },
    { id: 85, name: "Until Next Time", file: "DELTARUNESoundtrack/./085 Until Next Time.mp3", rating: 1500, comparisons: 0, duration: 62.12 },
    { id: 87, name: "Berdly (Rejected Concept)", file: "DELTARUNESoundtrack/./087 Berdly (Rejected Concept).mp3", rating: 1500, comparisons: 0, duration: 20.43 },
    { id: 88, name: "Flashback (Excerpt)", file: "DELTARUNESoundtrack/./088 Flashback (Excerpt).mp3", rating: 1500, comparisons: 0, duration: 32.03 },
    { id: 89, name: "Feature Presentation", file: "DELTARUNESoundtrack/./089 Feature Presentation.mp3", rating: 1500, comparisons: 0, duration: 42.34 },
    { id: 90, name: "And Now For Today’s Sponsors…!", file: "DELTARUNESoundtrack/./090 And Now For Today’s Sponsors…!.mp3", rating: 1500, comparisons: 0, duration: 31.48 },
    { id: 91, name: "MIKE, the BOARD, please!", file: "DELTARUNESoundtrack/./091 MIKE, the BOARD, please!.mp3", rating: 1500, comparisons: 0, duration: 32.89 },
    { id: 92, name: "Sandy Board", file: "DELTARUNESoundtrack/./092 Sandy Board.mp3", rating: 1500, comparisons: 0, duration: 78.39 },
    { id: 93, name: "Adventure Board", file: "DELTARUNESoundtrack/./093 Adventure Board.mp3", rating: 1500, comparisons: 0, duration: 59.32 },
    { id: 94, name: "Query-", file: "DELTARUNESoundtrack/./094 Query-.mp3", rating: 1500, comparisons: 0, duration: 24.82 },
    { id: 95, name: "Quiz!", file: "DELTARUNESoundtrack/./095 Quiz!.mp3", rating: 1500, comparisons: 0, duration: 76.83 },
    { id: 96, name: "Dig! Dig! To The Center of the Earth!", file: "DELTARUNESoundtrack/./096 Dig! Dig! To The Center of the Earth!.mp3", rating: 1500, comparisons: 0, duration: 7.99 },
    { id: 97, name: "Pushing Buddies", file: "DELTARUNESoundtrack/./097 Pushing Buddies.mp3", rating: 1500, comparisons: 0, duration: 19.83 },
    { id: 98, name: "Ruder Buster", file: "DELTARUNESoundtrack/./098 Ruder Buster.mp3", rating: 1500, comparisons: 0, duration: 106.68 },
    { id: 99, name: "Physical Challenge", file: "DELTARUNESoundtrack/./099 Physical Challenge.mp3", rating: 1500, comparisons: 0, duration: 107.08 },
    { id: 100, name: "Board Clear!", file: "DELTARUNESoundtrack/./100 Board Clear!.mp3", rating: 1500, comparisons: 0, duration: 34.82 },
    { id: 101, name: "Welcome to the Green Room", file: "DELTARUNESoundtrack/./101 Welcome to the Green Room.mp3", rating: 1500, comparisons: 0, duration: 90.41 },
    { id: 102, name: "Vapor Buster", file: "DELTARUNESoundtrack/./102 Vapor Buster.mp3", rating: 1500, comparisons: 0, duration: 120.03 },
    { id: 103, name: "Paradise, Paradise", file: "DELTARUNESoundtrack/./103 Paradise, Paradise.mp3", rating: 1500, comparisons: 0, duration: 150.88 },
    { id: 104, name: "Raft Ride", file: "DELTARUNESoundtrack/./104 Raft Ride.mp3", rating: 1500, comparisons: 0, duration: 69.43 },
    { id: 105, name: "SOUTH OF THE BORDER!!", file: "DELTARUNESoundtrack/./105 SOUTH OF THE BORDER!!.mp3", rating: 1500, comparisons: 0, duration: 12.04 },
    { id: 106, name: "Sound Check", file: "DELTARUNESoundtrack/./106 Sound Check.mp3", rating: 1500, comparisons: 0, duration: 25.63 },
    { id: 107, name: "Raise Up Your Bat", file: "DELTARUNESoundtrack/./107 Raise Up Your Bat.mp3", rating: 1500, comparisons: 0, duration: 133.62, felfebFile: "audio/felfeb/feb-dr/Raise Up Your Bat (With Lyrics) - The Deltarune Musical [uE0ePl8saaY].mp3" },
    { id: 108, name: "KING OF ROLYPOLY", file: "DELTARUNESoundtrack/./108 KING OF ROLYPOLY.mp3", rating: 1500, comparisons: 0, duration: 48.43 },
    { id: 109, name: "Glowing Snow", file: "DELTARUNESoundtrack/./109 Glowing Snow.mp3", rating: 1500, comparisons: 0, duration: 142.55 },
    { id: 110, name: "Big City Board", file: "DELTARUNESoundtrack/./110 Big City Board.mp3", rating: 1500, comparisons: 0, duration: 82.81 },
    { id: 111, name: "Doom Board", file: "DELTARUNESoundtrack/./111 Doom Board.mp3", rating: 1500, comparisons: 0, duration: 52.14 },
    { id: 112, name: "Metaphysical Challenge", file: "DELTARUNESoundtrack/./112 Metaphysical Challenge.mp3", rating: 1500, comparisons: 0, duration: 52.14 },
    { id: 113, name: "TV WORLD", file: "DELTARUNESoundtrack/./113 TV WORLD.mp3", rating: 1500, comparisons: 0, duration: 129.15, felfebFile: "audio/felfeb/feb-dr/tv world [XSQQugLHOr0].mp3" },
    { id: 114, name: "It’s TV Time!", file: "DELTARUNESoundtrack/./114 It’s TV Time!.mp3", rating: 1500, comparisons: 0, duration: 165.43, felfebFile: "audio/felfeb/feb-dr/It’s TV Time! (With Lyrics) - The Deltarune Musical [fpdCglI7BHs].mp3" },
    { id: 115, name: "Hall of Fame", file: "DELTARUNESoundtrack/./115 Hall of Fame.mp3", rating: 1500, comparisons: 0, duration: 30.33 },
    { id: 116, name: "Breath", file: "DELTARUNESoundtrack/./116 Breath.mp3", rating: 1500, comparisons: 0, duration: 14.68 },
    { id: 117, name: "Black Knife", file: "DELTARUNESoundtrack/./117 Black Knife.mp3", rating: 1500, comparisons: 0, duration: 117.19, felfebFile: "audio/felfeb/feb-dr/Black Knife (With Lyrics) - The Deltarune Musical [t8xndMeCBeE].mp3" },
    { id: 118, name: "Crickets", file: "DELTARUNESoundtrack/./118 Crickets.mp3", rating: 1500, comparisons: 0, duration: 36.96 },
    { id: 119, name: "Dump", file: "DELTARUNESoundtrack/./119 Dump.mp3", rating: 1500, comparisons: 0, duration: 40.88 },
    { id: 120, name: "SWORD", file: "DELTARUNESoundtrack/./120 SWORD.mp3", rating: 1500, comparisons: 0, duration: 132.44 },
    { id: 121, name: "NORTHERNLIGHT", file: "DELTARUNESoundtrack/./121 NORTHERNLIGHT.mp3", rating: 1500, comparisons: 0, duration: 22.88 },
    { id: 122, name: "GLACEIR", file: "DELTARUNESoundtrack/./122 GLACEIR.mp3", rating: 1500, comparisons: 0, duration: 67.24 },
    { id: 123, name: "BIT ROOTS", file: "DELTARUNESoundtrack/./123 BIT ROOTS.mp3", rating: 1500, comparisons: 0, duration: 77.09 },
    { id: 124, name: "ERAM", file: "DELTARUNESoundtrack/./124 ERAM.mp3", rating: 1500, comparisons: 0, duration: 15.80 },
    { id: 125, name: "BURNING EYES", file: "DELTARUNESoundtrack/./125 BURNING EYES.mp3", rating: 1500, comparisons: 0, duration: 65.12 },
    { id: 126, name: "Old wooden rafters", file: "DELTARUNESoundtrack/./126 Old wooden rafters.mp3", rating: 1500, comparisons: 0, duration: 99.00 },
    { id: 127, name: "Hymn", file: "DELTARUNESoundtrack/./127 Hymn.mp3", rating: 1500, comparisons: 0, duration: 33.83 },
    { id: 128, name: "Another day in hometown", file: "DELTARUNESoundtrack/./128 Another day in hometown.mp3", rating: 1500, comparisons: 0, duration: 139.08 },
    { id: 129, name: "Friends", file: "DELTARUNESoundtrack/./129 Friends.mp3", rating: 1500, comparisons: 0, duration: 85.66 },
    { id: 130, name: "Castle Funk", file: "DELTARUNESoundtrack/./130 Castle Funk.mp3", rating: 1500, comparisons: 0, duration: 176.67 },
    { id: 131, name: "Knock You Down!! (Rhythm Ver.)", file: "DELTARUNESoundtrack/./131 Knock You Down!! (Rhythm Ver.).mp3", rating: 1500, comparisons: 0, duration: 137.87 },
    { id: 132, name: "Gingerbread House", file: "DELTARUNESoundtrack/./132 Gingerbread House.mp3", rating: 1500, comparisons: 0, duration: 87.80 },
    { id: 133, name: "The distance between two", file: "DELTARUNESoundtrack/./133 The distance between two.mp3", rating: 1500, comparisons: 0, duration: 42.71 },
    { id: 134, name: "C", file: "DELTARUNESoundtrack/./134 C.mp3", rating: 1500, comparisons: 0, duration: 41.64 },
    { id: 135, name: "ATRIUM", file: "DELTARUNESoundtrack/./135 ATRIUM.mp3", rating: 1500, comparisons: 0, duration: 60.03 },
    { id: 136, name: "Dark Sanctuary", file: "DELTARUNESoundtrack/./136 Dark Sanctuary.mp3", rating: 1500, comparisons: 0, duration: 106.14 },
    { id: 137, name: "From Now On (Battle 2)", file: "DELTARUNESoundtrack/./137 From Now On (Battle 2).mp3", rating: 1500, comparisons: 0, duration: 108.72 },
    { id: 138, name: "Gyaa Ha ha!", file: "DELTARUNESoundtrack/./138 Gyaa Ha ha!.mp3", rating: 1500, comparisons: 0, duration: 75.28 },
    { id: 139, name: "Fireplace", file: "DELTARUNESoundtrack/./139 Fireplace.mp3", rating: 1500, comparisons: 0, duration: 157.54 },
    { id: 140, name: "A DARK ZONE", file: "DELTARUNESoundtrack/./140 A DARK ZONE.mp3", rating: 1500, comparisons: 0, duration: 138.03, felfebFile: "audio/felfeb/feb-dr/A Dark Zone (With Lyrics) - The Deltarune Musical [ldpVBJzvGRM].mp3" },
    { id: 141, name: "Mysterious Ringing", file: "DELTARUNESoundtrack/./141 Mysterious Ringing.mp3", rating: 1500, comparisons: 0, duration: 22.20 },
    { id: 142, name: "Ever Higher", file: "DELTARUNESoundtrack/./142 Ever Higher.mp3", rating: 1500, comparisons: 0, duration: 87.30 },
    { id: 143, name: "Wise words", file: "DELTARUNESoundtrack/./143 Wise words.mp3", rating: 1500, comparisons: 0, duration: 42.71 },
    { id: 144, name: "Piano that may not be played that well", file: "DELTARUNESoundtrack/./144 Piano that may not be played that well.mp3", rating: 1500, comparisons: 0, duration: 42.29 },
    { id: 145, name: "Hammer of Justice", file: "DELTARUNESoundtrack/./145 Hammer of Justice.mp3", rating: 1500, comparisons: 0, duration: 133.38 },
    { id: 146, name: "12am", file: "DELTARUNESoundtrack/./146 12am.mp3", rating: 1500, comparisons: 0, duration: 34.90 },
    { id: 147, name: "The Second Sanctuary", file: "DELTARUNESoundtrack/./147 The Second Sanctuary.mp3", rating: 1500, comparisons: 0, duration: 166.64 },
    { id: 148, name: "Ripple", file: "DELTARUNESoundtrack/./148 Ripple.mp3", rating: 1500, comparisons: 0, duration: 151.43 },
    { id: 149, name: "13am", file: "DELTARUNESoundtrack/./149 13am.mp3", rating: 1500, comparisons: 0, duration: 86.33 },
    { id: 150, name: "The Third Sanctuary", file: "DELTARUNESoundtrack/./150 The Third Sanctuary.mp3", rating: 1500, comparisons: 0, duration: 247.46 },
    { id: 151, name: "Dark Place", file: "DELTARUNESoundtrack/./151 Dark Place.mp3", rating: 1500, comparisons: 0, duration: 58.98 },
    { id: 152, name: "Heavy Footsteps", file: "DELTARUNESoundtrack/./152 Heavy Footsteps.mp3", rating: 1500, comparisons: 0, duration: 38.43 },
    { id: 153, name: "Crumbling Tower", file: "DELTARUNESoundtrack/./153 Crumbling Tower.mp3", rating: 1500, comparisons: 0, duration: 169.09 },
    { id: 154, name: "SPAWN", file: "DELTARUNESoundtrack/./154 SPAWN.mp3", rating: 1500, comparisons: 0, duration: 71.16 },
    { id: 155, name: "GUARDIAN", file: "DELTARUNESoundtrack/./155 GUARDIAN.mp3", rating: 1500, comparisons: 0, duration: 226.32 },
    { id: 156, name: "Need a hand!-", file: "DELTARUNESoundtrack/./156 Need a hand!-.mp3", rating: 1500, comparisons: 0, duration: 46.58 },
    { id: 157, name: "The place where it rained", file: "DELTARUNESoundtrack/./157 The place where it rained.mp3", rating: 1500, comparisons: 0, duration: 172.77 },
    { id: 158, name: "The Ol’ Jitterbug", file: "DELTARUNESoundtrack/./158 The Ol’ Jitterbug.mp3", rating: 1500, comparisons: 0, duration: 22.20 },
    { id: 159, name: "Neverending Night", file: "DELTARUNESoundtrack/./159 Neverending Night.mp3", rating: 1500, comparisons: 0, duration: 99.84 },
    { id: 160, name: "The LEGEND...-", file: "DELTARUNESoundtrack/./160 The LEGEND...-.mp3", rating: 1500, comparisons: 0, duration: 26.23 },
    { id: 161, name: "With Hope Crossed On Our Hearts", file: "DELTARUNESoundtrack/./161 With Hope Crossed On Our Hearts.mp3", rating: 1500, comparisons: 0, duration: 99.03 },
    { id: 162, name: "Volume Adjustment", file: "DELTARUNESoundtrack/./162 Volume Adjustment.mp3", rating: 1500, comparisons: 0, duration: 36.41 },
    { id: 163, name: "Catswing", file: "DELTARUNESoundtrack/./163 Catswing.mp3", rating: 1500, comparisons: 0, duration: 118.20 },
    { id: 164, name: "AIRWAVES", file: "DELTARUNESoundtrack/./164 AIRWAVES.mp3", rating: 1500, comparisons: 0, duration: 120.03 },
    { id: 165, name: "Concert for you", file: "DELTARUNESoundtrack/./165 Concert for you.mp3", rating: 1500, comparisons: 0, duration: 2.40 },
    // expanded hidden tracks. don't ask me for more.
    // corrected hidden tracks from deltarune.wiki. .ogg only.
    { id: 201, name: "man", file: "DELTARUNESoundtrack/man.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 11.19 },
    { id: 202, name: "man_nes", file: "DELTARUNESoundtrack/man_nes.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 9.00 },
    { id: 203, name: "man_2", file: "DELTARUNESoundtrack/man_2.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 26.48 },
    { id: 204, name: "find_her", file: "DELTARUNESoundtrack/find_her.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 76.80 },
    { id: 205, name: "alley_ambience", file: "DELTARUNESoundtrack/alley_ambience.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 25.85 },
    { id: 206, name: "alt_church_lobby", file: "DELTARUNESoundtrack/alt_church_lobby.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 20.84 },
    { id: 207, name: "ambientwater_weird", file: "DELTARUNESoundtrack/ambientwater_weird.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 6.00 },
    { id: 208, name: "audio_drone", file: "DELTARUNESoundtrack/audio_drone.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 8.74 },
    { id: 209, name: "baci_distort", file: "DELTARUNESoundtrack/baci_distort.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 31.49 },
    { id: 210, name: "board_ocean", file: "DELTARUNESoundtrack/board_ocean.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 14.19 },
    { id: 211, name: "ch4_first_intro", file: "DELTARUNESoundtrack/ch4_first_intro.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 17.68 },
    { id: 212, name: "cool_beat", file: "DELTARUNESoundtrack/cool_beat.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 1.59 },
    { id: 213, name: "honksong", file: "DELTARUNESoundtrack/honksong.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 61.64 },
    { id: 214, name: "jitterbug_muffled", file: "DELTARUNESoundtrack/jitterbug_muffled.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 33.55 },
    { id: 215, name: "lancer_annoying", file: "DELTARUNESoundtrack/lancer_annoying.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 42.43 },
    { id: 216, name: "pianpian", file: "DELTARUNESoundtrack/pianpian.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 21.23 },
    { id: 217, name: "smallpiano_room", file: "DELTARUNESoundtrack/smallpiano_room.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 14.17 },
    { id: 218, name: "strongwind_loop", file: "DELTARUNESoundtrack/strongwind_loop.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 12.84 },
    { id: 219, name: "mike_music_reset", file: "DELTARUNESoundtrack/mike_music_reset.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 5.05 },
    { id: 220, name: "w", file: "DELTARUNESoundtrack/w.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 5.14 },
    { id: 221, name: "kris_piano_sevenfour", file: "DELTARUNESoundtrack/kris_piano_sevenfour.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 70.89 },
    { id: 222, name: "kris_piano_quiz", file: "DELTARUNESoundtrack/kris_piano_quiz.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 17.79 },
    { id: 223, name: "kris_piano_lancer_waltz", file: "DELTARUNESoundtrack/kris_piano_lancer_waltz.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 80.40 },
    { id: 224, name: "kris_piano_rouxls", file: "DELTARUNESoundtrack/kris_piano_rouxls.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 52.70 },
    { id: 225, name: "kris_piano_waitingroom", file: "DELTARUNESoundtrack/kris_piano_waitingroom.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 94.40 },
    { id: 226, name: "kris_piano_shop", file: "DELTARUNESoundtrack/kris_piano_shop.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 53.89 },
    { id: 227, name: "kris_piano_last_prophecy", file: "DELTARUNESoundtrack/kris_piano_last_prophecy.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 58.14 },
    { id: 228, name: "kris_piano_prophecy", file: "DELTARUNESoundtrack/kris_piano_prophecy.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 37.75 },
    { id: 229, name: "cybercity_alt", file: "DELTARUNESoundtrack/cybercity_alt.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 141.47 },
    { id: 230, name: "berdly_battle", file: "DELTARUNESoundtrack/berdly_battle.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 17.45 },
    { id: 231, name: "me", file: "DELTARUNESoundtrack/me.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 6.26 },
    { id: 232, name: "sinedrone_high", file: "DELTARUNESoundtrack/sinedrone_high.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 11.03 },
    { id: 233, name: "ominous_worse", file: "DELTARUNESoundtrack/ominous_worse.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 7.37 },
    { id: 234, name: "tinnitus", file: "DELTARUNESoundtrack/tinnitus.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 48.00 },
    { id: 235, name: "annoying_prophecy", file: "DELTARUNESoundtrack/annoying_prophecy.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 15.16 },
    { id: 236, name: "audio_menu", file: "DELTARUNESoundtrack/audio_menu.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 45.23 },
    { id: 237, name: "cyber_battle", file: "DELTARUNESoundtrack/cyber_battle.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 24.00 },
    { id: 238, name: "cybercity_old", file: "DELTARUNESoundtrack/cybercity_old.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 105.00 },
    { id: 239, name: "noelle", file: "DELTARUNESoundtrack/noelle.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 53.58 },
    { id: 240, name: "spamton_house", file: "DELTARUNESoundtrack/spamton_house.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 17.64 },
    { id: 241, name: "static_placeholder", file: "DELTARUNESoundtrack/static_placeholder.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 13.42 },
    { id: 242, name: "thrash_rating", file: "DELTARUNESoundtrack/thrash_rating.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 10.67 },
    { id: 243, name: "field_of_hopes_crisp", file: "DELTARUNESoundtrack/field_of_hopes_crisp.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 15.08 },
    { id: 244, name: "battle_preview_crisp", file: "DELTARUNESoundtrack/battle_preview_crisp.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 14.99 },
    { id: 245, name: "nightmare_boss_links", file: "DELTARUNESoundtrack/nightmare_boss_links.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 58.58 },
    { id: 246, name: "church_test", file: "DELTARUNESoundtrack/church_test.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 166.63 },
    { id: 247, name: "sinedrone_danger", file: "DELTARUNESoundtrack/sinedrone_danger.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 1.06 },
    { id: 248, name: "wet_tapdancing", file: "DELTARUNESoundtrack/wet_tapdancing.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 9.38 },
    { id: 249, name: "wet_tapdancing2", file: "DELTARUNESoundtrack/wet_tapdancing2.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 9.23 },
    { id: 250, name: "wet_tapdancing_failed", file: "DELTARUNESoundtrack/wet_tapdancing_failed.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 9.23 },
    { id: 251, name: "dogcheck", file: "DELTARUNESoundtrack/dogcheck.ogg", rating: 1500, comparisons: 0, hidden: true, duration: 15.16 },
    // scrapped songs from tby fox newsletter. i hate being a completionsist.
    { id: 301, name: "Castle Town Unfinished", file: "DELTARUNESoundtrack/Castle Town Unfinished.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 128.11 },
    { id: 302, name: "GIGA Queen Old", file: "DELTARUNESoundtrack/GIGA Queen Old.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 88.7 },
    { id: 303, name: "Power of SPAMTON", file: "DELTARUNESoundtrack/Power of SPAMTON.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 135.84 },
    { id: 304, name: "Power of SPAMTON Older", file: "DELTARUNESoundtrack/Power of SPAMTON Older.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 135.84 },
    { id: 305, name: "Printer Noise", file: "DELTARUNESoundtrack/Printer Noise.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 5.38 },
    { id: 306, name: "Queen Battle Original", file: "DELTARUNESoundtrack/Queen Battle Original.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 96.12 },
    { id: 307, name: "Rouxls Battle Old", file: "DELTARUNESoundtrack/Rouxls Battle Old.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 96.1 },
    { id: 308, name: "Spamton Battle Forgotten", file: "DELTARUNESoundtrack/Spamton Battle Forgotten.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 60.98 },
    { id: 309, name: "Unused Power of NEO", file: "DELTARUNESoundtrack/Unused Power of NEO.mp3", rating: 1500, comparisons: 0, hidden: true, duration: 162.31 },
];

// expose to the world. or just the window. whatever.
window.songList = songList;


