const utSongList = [
	{
		id: 1001,
		name: "Once Upon a Time",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 01 Once Upon a Time.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 89.0,
	},
	{
		id: 1002,
		name: "Start Menu",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 02 Start Menu.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 32.03,
	},
	{
		id: 1003,
		name: "Your Best Friend",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 03 Your Best Friend.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 23.28,
	},
	{
		id: 1004,
		name: "Fallen Down",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 04 Fallen Down.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 57.86,
	},
	{
		id: 1005,
		name: "Ruins",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 05 Ruins.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 92.32,
	},
	{
		id: 1006,
		name: "Uwa!! So Temperate\u266b",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 06 Uwa!! So Temperate\u266b.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 56.61,
	},
	{
		id: 1007,
		name: "Anticipation",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 07 Anticipation.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 22.33,
	},
	{
		id: 1008,
		name: "Unnecessary Tension",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 08 Unnecessary Tension.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 17.32,
	},
	{
		id: 1009,
		name: "Enemy Approaching",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 09 Enemy Approaching.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 56.42,
	},
	{
		id: 1010,
		name: "Ghost Fight",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 10 Ghost Fight.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 56.58,
	},
	{
		id: 1011,
		name: "Determination",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 11 Determination.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 50.39,
	},
	{
		id: 1012,
		name: "Home",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 12 Home.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 123.04,
	},
	{
		id: 1013,
		name: "Home (Music Box)",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 13 Home (Music Box).mp3",
		rating: 1500,
		comparisons: 0,
		duration: 122.93,
	},
	{
		id: 1014,
		name: "Heartache",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 14 Heartache.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 108.49,
		felfebFile:
			"audio/felfeb/feb-ut/Heartache (With Lyrics) - The Undertale Musical [kJgTTR5wE3M].mp3",
	},
	{
		id: 1015,
		name: "sans.",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 15 sans..mp3",
		rating: 1500,
		comparisons: 0,
		duration: 50.65,
	},
	{
		id: 1016,
		name: "Nyeh Heh Heh!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 16 Nyeh Heh Heh!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 32.44,
	},
	{
		id: 1017,
		name: "Snowy",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 17 Snowy.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 104.31,
	},
	{
		id: 1018,
		name: "Uwa!! So Holiday\u266b",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 18 Uwa!! So Holiday\u266b.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 30.04,
	},
	{
		id: 1019,
		name: "Dogbass",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 19 Dogbass.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 6.58,
	},
	{
		id: 1020,
		name: "Mysterious Place",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 20 Mysterious Place.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 44.83,
	},
	{
		id: 1021,
		name: "Dogsong",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 21 Dogsong.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 37.33,
	},
	{
		id: 1022,
		name: "Snowdin Town",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 22 Snowdin Town.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 76.2,
	},
	{
		id: 1023,
		name: "Shop",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 23 Shop.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 50.31,
	},
	{
		id: 1024,
		name: "Bonetrousle",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 24 Bonetrousle.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 57.63,
	},
	{
		id: 1025,
		name: "Dating Start!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 25 Dating Start!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 116.9,
	},
	{
		id: 1026,
		name: "Dating Tense!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 26 Dating Tense!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 26.17,
	},
	{
		id: 1027,
		name: "Dating Fight!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 27 Dating Fight!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 35.94,
	},
	{
		id: 1028,
		name: "Premonition",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 28 Premonition.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 61.81,
	},
	{
		id: 1029,
		name: "Danger Mystery",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 29 Danger Mystery.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 18.47,
	},
	{
		id: 1030,
		name: "Undyne",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 30 Undyne.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 45.95,
	},
	{
		id: 1031,
		name: "Waterfall",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 31 Waterfall.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 126.9,
	},
	{
		id: 1032,
		name: "Run!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 32 Run!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 26.91,
	},
	{
		id: 1033,
		name: "Quiet Water",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 33 Quiet Water.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 32.03,
	},
	{
		id: 1034,
		name: "Memory",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 34 Memory.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 75.05,
	},
	{
		id: 1035,
		name: "Bird That Carries You Over A Disproportionately Small Gap",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 35 Bird That Carries You Over A Disproportionately Small Gap.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 25.13,
	},
	{
		id: 1036,
		name: "Dummy!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 36 Dummy!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 145.95,
	},
	{
		id: 1037,
		name: "Pathetic House",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 37 Pathetic House.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 38.82,
	},
	{
		id: 1038,
		name: "Spooktune",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 38 Spooktune.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 23.64,
	},
	{
		id: 1039,
		name: "Spookwave",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 39 Spookwave.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 25.13,
	},
	{
		id: 1040,
		name: "Ghouliday",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 40 Ghouliday.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 12.88,
	},
	{
		id: 1041,
		name: "Chill",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 41 Chill.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 56.32,
	},
	{
		id: 1042,
		name: "Thundersnail",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 42 Thundersnail.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 42.42,
	},
	{
		id: 1043,
		name: "Temmie Village",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 43 Temmie Village.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 57.89,
	},
	{
		id: 1044,
		name: "Tem Shop",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 44 Tem Shop.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 45.27,
	},
	{
		id: 1045,
		name: "NGAHHH!!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 45 NGAHHH!!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 82.6,
	},
	{
		id: 1046,
		name: "Spear of Justice",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 46 Spear of Justice.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 115.49,
		felfebFile:
			"audio/felfeb/feb-ut/Spear Of Justice (With Lyrics) - The Undertale Musical [cXadznTVXDE].mp3",
	},
	{
		id: 1047,
		name: "Ooo",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 47 Ooo.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 14.18,
	},
	{
		id: 1048,
		name: "Alphys",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 48 Alphys.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 85.29,
	},
	{
		id: 1049,
		name: "It's Showtime!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 49 It's Showtime!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 46.16,
	},
	{
		id: 1050,
		name: "Metal Crusher",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 50 Metal Crusher.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 63.22,
	},
	{
		id: 1051,
		name: "Another Medium",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 51 Another Medium.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 142.18,
	},
	{
		id: 1052,
		name: "Uwa!! So HEATS!!\u266b",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 52 Uwa!! So HEATS!!\u266b.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 34.01,
	},
	{
		id: 1053,
		name: "Stronger Monsters",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 53 Stronger Monsters.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 63.16,
	},
	{
		id: 1054,
		name: "Hotel",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 54 Hotel.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 87.77,
	},
	{
		id: 1055,
		name: "Can You Really Call This A Hotel, I Didn't Receive A Mint On My Pillow Or Anything",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 55 Can You Really Call This A Hotel, I Didn't Receive A Mint On My Pillow Or Anything.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 61.47,
	},
	{
		id: 1056,
		name: "Confession",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 56 Confession.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 42.11,
	},
	{
		id: 1057,
		name: "Live Report",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 57 Live Report.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 17.79,
	},
	{
		id: 1058,
		name: "Death Report",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 58 Death Report.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 47.15,
	},
	{
		id: 1059,
		name: "Spider Dance",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 59 Spider Dance.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 106.48,
		felfebFile:
			"audio/felfeb/feb-ut/Spider Dance (With Lyrics) - The Undertale Musical [FC-TH8DU8so].mp3",
	},
	{
		id: 1060,
		name: "Wrong Enemy !?",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 60 Wrong Enemy !?.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 58.44,
	},
	{
		id: 1061,
		name: "Oh! One True Love",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 61 Oh! One True Love.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 84.04,
	},
	{
		id: 1062,
		name: "Oh! Dungeon",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 62 Oh! Dungeon.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 32.89,
	},
	{
		id: 1063,
		name: "It's Raining Somewhere Else",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 63 It's Raining Somewhere Else.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 170.34,
	},
	{
		id: 1064,
		name: "CORE Approach",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 64 CORE Approach.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 12.09,
	},
	{
		id: 1065,
		name: "CORE",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 65 CORE.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 166.43,
	},
	{
		id: 1066,
		name: "Last Episode!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 66 Last Episode!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 7.65,
	},
	{
		id: 1067,
		name: "Oh My...",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 67 Oh My....mp3",
		rating: 1500,
		comparisons: 0,
		duration: 14.52,
	},
	{
		id: 1068,
		name: "Death by Glamour",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 68 Death by Glamour.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 134.64,
		felfebFile:
			"audio/felfeb/feb-ut/Death By Glamour (With Lyrics) - The Undertale Musical [cf_GIbnsC6E].mp3",
	},
	{
		id: 1069,
		name: "For the Fans",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 69 For the Fans.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 107.28,
	},
	{
		id: 1070,
		name: "Long Elevator",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 70 Long Elevator.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 20.06,
	},
	{
		id: 1071,
		name: "Undertale",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 71 Undertale.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 381.57,
	},
	{
		id: 1072,
		name: "Song That Might Play When You Fight Sans",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 72 Song That Might Play When You Fight Sans.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 62.04,
	},
	{
		id: 1073,
		name: "The Choice",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 73 The Choice.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 132.57,
	},
	{
		id: 1074,
		name: "Small Shock",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 74 Small Shock.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 14.16,
	},
	{
		id: 1075,
		name: "Barrier",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 75 Barrier.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 31.19,
	},
	{
		id: 1076,
		name: "Bergentr\u00fcckung",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 76 Bergentr\u00fcckung.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 21.26,
	},
	{
		id: 1077,
		name: "ASGORE",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 77 ASGORE.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 156.03,
	},
	{
		id: 1078,
		name: "You Idiot",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 78 You Idiot.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 34.59,
	},
	{
		id: 1079,
		name: "Your Best Nightmare",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 79 Your Best Nightmare.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 240.04,
		felfebFile:
			"audio/felfeb/feb-ut/Your Best Nightmare (With Lyrics) - The Undertale Musical [xEuAr3xUEV0].mp3",
	},
	{
		id: 1080,
		name: "Finale",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 80 Finale.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 112.46,
		felfebFile:
			"audio/felfeb/feb-ut/Finale (With Lyrics) - The Undertale Musical [T8w6o6gzTpY].mp3",
	},
	{
		id: 1081,
		name: "An Ending",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 81 An Ending.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 208.85,
	},
	{
		id: 1082,
		name: "She's Playing Piano",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 82 She's Playing Piano.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 18.89,
	},
	{
		id: 1083,
		name: "Here We Are",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 83 Here We Are.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 126.22,
	},
	{
		id: 1084,
		name: "Amalgam",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 84 Amalgam.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 80.04,
	},
	{
		id: 1085,
		name: "Fallen Down (Reprise)",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 85 Fallen Down (Reprise).mp3",
		rating: 1500,
		comparisons: 0,
		duration: 150.6,
	},
	{
		id: 1086,
		name: "Don't Give Up",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 86 Don't Give Up.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 122.04,
	},
	{
		id: 1087,
		name: "Hopes and Dreams",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 87 Hopes and Dreams.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 181.32,
	},
	{
		id: 1088,
		name: "Burn in Despair!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 88 Burn in Despair!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 21.37,
	},
	{
		id: 1089,
		name: "SAVE the World",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 89 SAVE the World.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 113.37,
	},
	{
		id: 1090,
		name: "His Theme",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 90 His Theme.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 125.36,
	},
	{
		id: 1091,
		name: "Final Power",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 91 Final Power.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 18.94,
	},
	{
		id: 1092,
		name: "Reunited",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 92 Reunited.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 284.11,
	},
	{
		id: 1093,
		name: "Menu (Full)",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 93 Menu (Full).mp3",
		rating: 1500,
		comparisons: 0,
		duration: 32.03,
	},
	{
		id: 1094,
		name: "Respite",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 94 Respite.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 114.05,
	},
	{
		id: 1095,
		name: "Bring It In, Guys!",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 95 Bring It In, Guys!.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 252.21,
	},
	{
		id: 1096,
		name: "Last Goodbye",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 96 Last Goodbye.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 135.24,
	},
	{
		id: 1097,
		name: "But the Earth Refused to Die",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 97 But the Earth Refused to Die.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 34.32,
	},
	{
		id: 1098,
		name: "Battle Against a True Hero",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 98 Battle Against a True Hero.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 156.84,
	},
	{
		id: 1099,
		name: "Power of -NEO-",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 99 Power of -NEO-.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 30.67,
	},
	{
		id: 1100,
		name: "MEGALOVANIA",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 100 MEGALOVANIA.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 156.03,
		felfebFile:
			"audio/felfeb/feb-ut/Megalovania (With Lyrics) - The Undertale Musical [CCnvjYfU2Hc].mp3",
	},
	{
		id: 1101,
		name: "Good Night",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 101 Good Night.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 31.01,
	},
	{
		id: 1102,
		name: "Abc 123 a new laughing",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 102 Abc 123 a new laughing.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 6.19,
		hidden: true,
	},
	{
		id: 1103,
		name: "Abc 123 a old",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 103 Abc 123 a old.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 25.63,
		hidden: true,
	},
	{
		id: 1104,
		name: "Alphys lab",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 104 Alphys lab.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 78.73,
		hidden: true,
	},
	{
		id: 1105,
		name: "Dance of Dog",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 105 Dance of Dog.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 13.77,
		hidden: true,
	},
	{
		id: 1107,
		name: "Dogtroid",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 107 Dogtroid.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 34.32,
		hidden: true,
	},
	{
		id: 1108,
		name: "Finale (unused)",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 108 Finale.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 11.42,
		hidden: true,
	},
	{
		id: 1109,
		name: "Gaster's Theme",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 109 Gaster's Theme.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 17.53,
		hidden: true,
	},
	{
		id: 1111,
		name: "Grandpa Semi",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 111 Grandpa Semi.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 5.09,
		hidden: true,
	},
	{
		id: 1112,
		name: "Happy Town",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 112 Happy Town.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 1.36,
		hidden: true,
	},
	{
		id: 1113,
		name: "Meat Factory",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 113 Meat Factory.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 1.78,
		hidden: true,
	},
	{
		id: 1114,
		name: "Mus kingdescription",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 114 Mus kingdescription.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 64.05,
		hidden: true,
	},
	{
		id: 1115,
		name: "Mus ruinspiano",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 115 Mus ruinspiano.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 69.38,
		hidden: true,
	},
	{
		id: 1116,
		name: "Mus smile",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 116 Mus smile.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 79.18,
		hidden: true,
	},
	{
		id: 1117,
		name: "Mus star",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 117 Mus star.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 45.77,
		hidden: true,
	},
	{
		id: 1118,
		name: "Patient",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 118 Patient.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 59.12,
		hidden: true,
	},
	{
		id: 1119,
		name: "Sigh of Dog",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 119 Sigh of Dog.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 29.73,
		hidden: true,
	},
	{
		id: 1120,
		name: "Trouble Dingle",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 120 Trouble Dingle.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 1.46,
		hidden: true,
	},
	{
		id: 1121,
		name: "Undertale (Soundtrack)",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 121 Undertale (Soundtrack).mp3",
		rating: 1500,
		comparisons: 0,
		duration: 244.04,
		hidden: true,
	},
	{
		id: 1122,
		name: "Undyne battle",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 122 Undyne battle.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 90.04,
		hidden: true,
	},
	{
		id: 1123,
		name: "Wrong Number Song",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 123 Wrong Number Song.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 5.59,
		hidden: true,
	},
	{
		id: 1124,
		name: "Your Best Nightmare (unused)",
		file: "UNDERTALEsoundtrack/toby fox - UNDERTALE Soundtrack - 124 Your Best Nightmare.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 25.31,
		hidden: true,
	},
	{
		id: 1201,
		name: "Mad Mew Mew",
		file: "UNDERTALEsoundtrack/bonus/Mad Mew Mew.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 144.26,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1202,
		name: "Abandoned Town (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/01_Abandoned_Town.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 62.57,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1203,
		name: "Doghole (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/02_Doghole.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 43.75,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1204,
		name: "Memory (10 Years Later)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/03_Memory_10_Years_Later.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 105.02,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1205,
		name: "Pseudo Legendary Tree (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/04_Pseudo_Legendary_Tree.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 26.52,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1206,
		name: "School (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/05_School.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 81.77,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1207,
		name: "Snowdrift (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/06_Snowdrift.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 76.92,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1208,
		name: "Snowed Inn Jazz (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/07_Snowed_Inn_Jazz.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 42.46,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1209,
		name: "Song That Plays When Somebody Verses Sans (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/08_Song_That_Plays_When_Somebody_Verses_Sans.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 105.31,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1210,
		name: "Strongerer Monsters (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/09_Strongerer_Monsters.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 71.14,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1211,
		name: "Ultranap (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/10_Ultranap.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 10.7,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1212,
		name: "Underwater Town (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/11_Underwater_Town.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 80.04,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1213,
		name: "What's up? (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/12_Whats_up.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 114.7,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1214,
		name: "Wrong Number (Remix) (10th Anniversary)",
		file: "UNDERTALEsoundtrack/bonus/10th_Anniversary/13_Wrong_Number_Remix.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 6.74,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1301,
		name: "Ball Chime",
		file: "UNDERTALEsoundtrack/hidden/Ball Chime.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 3.18,
		hidden: true,
	},
	{
		id: 1302,
		name: "Bereavement",
		file: "UNDERTALEsoundtrack/hidden/Bereavement.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 357.72,
		hidden: true,
	},
	{
		id: 1303,
		name: "Megalo Strike Back",
		file: "UNDERTALEsoundtrack/hidden/Megalo Strike Back.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 163.39,
		hidden: true,
	},
	{
		id: 1304,
		name: "Undertale Release Trailer",
		file: "UNDERTALEsoundtrack/hidden/Undertale Release Trailer.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 74.93,
		hidden: true,
	},
	{
		id: 1305,
		name: "Undertale Xbox One Announce Trailer",
		file: "UNDERTALEsoundtrack/hidden/Undertale Xbox One Announce Trailer.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 64.25,
		hidden: true,
	},
	{
		id: 1306,
		name: "Papyrus' Cool Song",
		file: "UNDERTALEsoundtrack/hidden/Papyrus' Cool Song.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 14.33,
		hidden: true,
	},
	{
		id: 1307,
		name: "Ice Cream",
		file: "UNDERTALEsoundtrack/hidden/Ice Cream.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 61.82,
		hidden: true,
	},
	{
		id: 1308,
		name: "Undertale Nintendo Switch Trailer",
		file: "UNDERTALEsoundtrack/hidden/Undertale Nintendo Switch Trailer.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 87.6,
		hidden: true,
	},
	{
		id: 1309,
		name: "mus_toomuch",
		file: "UNDERTALEsoundtrack/hidden/mus_toomuch.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 50.11,
		hidden: true,
	},
	{
		id: 1310,
		name: "mus_zzz_c",
		file: "UNDERTALEsoundtrack/hidden/mus_zzz_c.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 8.11,
		hidden: true,
	},
	{
		id: 1311,
		name: "Ball Chime (Mystery)",
		file: "UNDERTALEsoundtrack/hidden/Ball Chime (Mystery).mp3",
		rating: 1500,
		comparisons: 0,
		duration: 36.48,
		hidden: true,
	},
	{
		id: 1312,
		name: "Pre-Dummy",
		file: "UNDERTALEsoundtrack/hidden/Pre-Dummy.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 28.06,
		hidden: true,
	},
	{
		id: 1313,
		name: "Room Of Dog",
		file: "UNDERTALEsoundtrack/hidden/Room Of Dog.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 72.19,
		hidden: true,
	},
	{
		id: 1314,
		name: "Mysterious Shrine",
		file: "UNDERTALEsoundtrack/hidden/Mysterious Shrine.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 48.79,
		hidden: true,
	},
	{
		id: 1315,
		name: "Absolutely Overfamiliar Shrine",
		file: "UNDERTALEsoundtrack/hidden/Absolutely Overfamiliar Shrine.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 18.89,
		hidden: true,
	},
	{
		id: 1316,
		name: "Dog Dating",
		file: "UNDERTALEsoundtrack/hidden/Dog Dating.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 22.85,
		hidden: true,
	},
	{
		id: 1317,
		name: "mus_bad",
		file: "UNDERTALEsoundtrack/hidden/mus_bad.mp3",
		rating: 1500,
		comparisons: 0,
		duration: 10.13,
		hidden: true,
	},
	{
		id: 1318,
		name: "Dating Start! (FM Ver)",
		file: "UNDERTALEsoundtrack/hidden/Dating Start! (FM Ver).mp3",
		rating: 1500,
		comparisons: 0,
		duration: 167.63,
		hidden: true,
	},
	// genocide tracks.
	{
		id: 1401,
		name: "Another Medium (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Another Medium (Genocide) [Q7gUvvWWiUQ].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 284.64,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1402,
		name: "Anticipation (Post-Genocide)",
		file: "Undertale - Genocide OST/Undertale - Anticipation (Post-Genocide) [7e18anERknc].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 112.27,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1403,
		name: "Bonetrousle (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Bonetrousle (Genocide) [RIqkAlcoT6k].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 288.72,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1405,
		name: "CORE (Genocide)",
		file: "Undertale - Genocide OST/Undertale - CORE (Genocide) [suOL_xKSx0k].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 333.17,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1406,
		name: "Dating Start! (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Dating Start! (Genocide) [72E7D24dN_o].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 468.17,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1407,
		name: "Hotel (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Hotel (Genocide) [aSg7nl4dyvg].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 175.9,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1408,
		name: "In My Way (Anticipation Slow Ver.)",
		file: "Undertale - Genocide OST/Undertale - In My Way (Anticipation Slow Ver.) [CL_LLpyM2sE].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 89.81,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1409,
		name: "Quiet Water (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Quiet Water (Genocide) [Nd5Q_0cN5wA].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 58.56,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1410,
		name: "Small Shock (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Small Shock (Genocide) [RjbJ2ASRUA4].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 23.88,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1411,
		name: "Snowdin Town (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Snowdin Town (Genocide) [k-nATYGDCwo].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 305.28,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1412,
		name: "Snowy (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Snowy (Genocide) [qF58N1wQ8g4].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 174.12,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1413,
		name: "Temmie Village (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Temmie Village (Genocide) [rB48hLdu4AA].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 116.04,
		isBonus: true,
		hidden: true,
	},
	{
		id: 1414,
		name: "Waterfall (Genocide)",
		file: "Undertale - Genocide OST/Undertale - Waterfall (Genocide) [vXlzzF-s5c4].mp3",
		rating: 1500,
		comparisons: 0,
		duration: 977.26,
		isBonus: true,
		hidden: true,
	},
];

// done adding songs.
window.utSongList = utSongList;
